{% set name = "aim-ui" %}
{% set version = "3.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aim-ui-{{ version }}.tar.gz
  sha256: 52614968cd79a81ab48131633170fadbeae77a26e98d3a0618a0c92e9f67dbd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - aim_ui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aim-ui/
  summary: Aim UI
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gorarakelyan
    - synapticarbors
